# Generated by Django 5.2 on 2025-04-20 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('tahun', models.IntegerField()),
                ('harga_dasar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pinjaman_bank', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('suku_bunga', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('deskripsi', models.TextField()),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='showroom.car')),
            ],
        ),
    ]
