# Generated by Django 5.2 on 2025-04-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dibiayai_bank',
            field=models.BooleanField(default=False),
        ),
    ]
