# Generated by Django 5.2 on 2025-04-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_car_dibiayai_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='mobil',
            new_name='car',
        ),
    ]
