# Generated by Django 5.2 on 2025-04-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_rename_mobil_service_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='car',
            new_name='mobil',
        ),
    ]
